buildscript {
    ext {
        arcHash = '41219a4eb5'

        arcModule = { String name ->
            name = name.substring(name.lastIndexOf(':') + 1)
            return "com.github.Anuken.Arc:$name:$arcHash"
        }
    }

    repositories {
        mavenLocal()
        mavenCentral()
        google()
        maven { url 'https://jitpack.io' }
    }

    dependencies {
        classpath arcModule(":extensions:packer")
        classpath arcModule(":arc-core")
    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = 'release'

    ext {
        versionNumber = '4'
        versionModifier = 'Arc'
        versionType = 'unofficial'
        appName = 'Mindustry'

        getVersionString = {
            String buildVersion = getBuildVersion()
            return "$versionNumber-$versionModifier-$buildVersion"
        }

        getBuildVersion = {
            if (!project.hasProperty("buildversion")) return "custom build"
            return project.getProperties()["buildversion"]
        }

        getPackage = {
            return project.ext.mainClassName.substring(0, project.ext.mainClassName.indexOf("desktop") - 1)
        }

        generateLocales = {
            def output = 'en\n'
            def bundles = new File(project(':core').projectDir, 'assets/bundles/')
            bundles.listFiles().each { other ->
                if (other.name == "bundle.properties") return
                output += other.name.substring("bundle".length() + 1, other.name.lastIndexOf('.')) + "\n"
            }
            new File(project(':core').projectDir, 'assets/locales').text = output
        }

        writeVersion = {
            def pfile = new File(project(':core').projectDir, 'assets/version.properties')
            def props = new Properties()

            try {
                pfile.createNewFile()
            } catch (Exception ignored) {}

            if (pfile.exists()) {
                props.load(new FileInputStream(pfile))

                String buildid = getBuildVersion()

                props["type"] = versionType
                props["number"] = versionNumber
                props["modifier"] = versionModifier
                props["build"] = buildid

                props.store(pfile.newWriter(), "Autogenerated file. Do not modify.")
            }
        }
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
        maven { url 'https://jitpack.io' }
    }
}

configure(subprojects) {
    tasks.withType(JavaCompile) {
        targetCompatibility = JavaVersion.VERSION_17
        sourceCompatibility = JavaVersion.VERSION_17
        options.encoding = "UTF-8"
    }
}

project(":desktop") {
    apply plugin: "java-library"

    dependencies {
        implementation project(":core")
        implementation project(":kryonet")

        implementation arcModule("backends:backend-sdl")
        implementation arcModule("natives:natives-desktop")
        implementation arcModule("natives:natives-freetype-desktop")
        implementation arcModule("extensions:discord")
        implementation 'com.github.MinnDevelopment:java-discord-rpc:v2.0.0'
    }
}

project(":core") {
    apply plugin: "java-library"

    task copyDeps(type: Copy) {
        from configurations.annotationProcessor
        from configurations.compileClasspath
        into "deps"
    }

    task finish {
        generateLocales()
    }

    dependencies {
        build.finalizedBy(finish)

        implementation arcModule(":arc-core")
        implementation arcModule("extensions:freetype")

        compileOnly project(":annotations")
        annotationProcessor project(":annotations")
    }

    tasks.withType(JavaCompile) {
        options.compilerArgs << "-XprintProcessorInfo" << "-XprintRounds"
    }
}

project(":server") {
    apply plugin: "java-library"

    dependencies {
        implementation project(":core")
        implementation project(":kryonet")
        implementation arcModule("backends:backend-headless")
    }
}

project(":tests") {
    apply plugin: "java"

    dependencies {
        testImplementation project(":core")
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.1.0'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.1.0'
        testImplementation arcModule("backends:backend-headless")
    }

    test {
        useJUnitPlatform()
        workingDir = new File("../core/assets")
    }
}

project(":tools") {
    apply plugin: "java"

    dependencies {
        implementation project(":core")
    }
}

project(":annotations") {
    apply plugin: "java"

    dependencies {
        implementation 'com.squareup:javapoet:1.11.0'
    }
}

project(":kryonet") {
    apply plugin: "java-library"

    dependencies {
        implementation project(":core")
        implementation "org.lz4:lz4-java:1.4.1"
        implementation 'com.github.Anuken:kryonet:53b10247b1'
        implementation 'com.github.Anuken:WaifUPnP:05eb46bc577fd7674596946ba288c96c0cedd893'
    }
}
