buildscript {
	repositories {
		mavenLocal()
		mavenCentral()
		google()
		maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
	}
	dependencies {
		classpath 'com.mobidevelop.robovm:robovm-gradle-plugin:2.3.0'
	}
}

apply plugin: "robovm"

sourceSets.main.java.srcDirs = [ "src/" ]

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

ext {
	mainClassName = "io.anuke.mindustry.IOSLauncher"
}

launchIPhoneSimulator.dependsOn build
launchIPadSimulator.dependsOn build
launchIOSDevice.dependsOn build
createIPA.dependsOn build

robovm {
	archs = "thumbv7:arm64"
}
